### `r analita`

```{r}
# intervalli
lavoro_txt <- risultati[variable == "intervallo_lavoro", paste0(value, " ", udm_metrica)] |>
     paste0(collapse = "; ")
linearita_txt <- risultati[variable == "intervallo_linearita",
  ifelse(!is.na(value), 
    paste0(value, " ", udm_metrica),
    "non applicabile")] |> 
      paste0(collapse = "; ")
```

**LOQ**: `r risultati[variable == "loq", format_risultato(requisito_min, requisito_max, value, udm_metrica, esito)]`<br>
**Intervallo di lavoro**: `r lavoro_txt`<br> 
**Intervallo di linearità**: `r linearita_txt`<br>

```{r}
#| fig-cap: !expr paste0("Valori misurati per l'analita ", analita, 
#|   ". Sono mostrati anche il valore di riferimento, il valore medio delle misure e
#|   gli intervalli di copertura robusti calcolati mediante $k\\cdot\\text{MAD}$.")

grafici[, grafico_obj[[1]]]
```

```{r}
#| output: asis
livelli <- risultati[!is.na(livello), unique(livello)]

for (lvl in livelli) {
  env_child <- new.env()
  env_child$risultati <- risultati[livello == lvl]
  env_child$livello <- lvl
  knitr::knit_child("_includes/precisione_giustezza.qmd",
        envir = env_child,
        quiet = TRUE) |>
    cat()
  cat("\n\n\n")
}
```
